export type OccasionCalendar = "persian" | "hijri" | "gregorian";

export type SimpleOccasionRecord = {
  calendar: OccasionCalendar;
  month: number;
  day: number;
  title: string;
  isHoliday: boolean;
  fromYear?: number;
  toYear?: number;
};

export type IrregularOccasionRecord = {
  calendar: OccasionCalendar;
  title: string;
  isHoliday: boolean;
  fromYear?: number;
  toYear?: number;
} & (
  | { rule: "nth-weekday"; month: number; nth: number; weekday: number }
  | { rule: "last-weekday"; month: number; weekday: number; offset?: number }
  | { rule: "end-of-month"; month: number }
  | { rule: "single"; year: number; month: number; day: number }
);

export const SIMPLE_OCCASIONS: readonly SimpleOccasionRecord[] = [
  {
    calendar: "persian",
    month: 1,
    day: 1,
    title: "آغاز نوروز",
    isHoliday: true,
  },
  {
    calendar: "persian",
    month: 1,
    day: 2,
    title: "عید نوروز",
    isHoliday: true,
  },
  {
    calendar: "persian",
    month: 1,
    day: 2,
    title: "هجوم مأموران ستم‌شاهی پهلوی به مدرسهٔ فیضیهٔ قم (۱۳۴۲ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 2,
    title: "آغاز عملیات فتح‌المبین (۱۳۶۱ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 3,
    title: "عید نوروز",
    isHoliday: true,
  },
  {
    calendar: "persian",
    month: 1,
    day: 4,
    title: "عید نوروز",
    isHoliday: true,
  },
  {
    calendar: "persian",
    month: 1,
    day: 6,
    title: "زادروز زرتشت پیامبر",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 7,
    title: "روز هنرهای نمایشی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 12,
    title: "روز جمهوری اسلامی ایران",
    isHoliday: true,
  },
  {
    calendar: "persian",
    month: 1,
    day: 13,
    title: "روز طبیعت",
    isHoliday: true,
  },
  {
    calendar: "persian",
    month: 1,
    day: 15,
    title: "روز ذخایر ژنتیکی و زیستی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 18,
    title: "روز سلامتی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 19,
    title: "شهادت آیت‌اللّه سیدمحمدباقر صدر و خواهر ایشان بنت‌الهدی به دست حکومت بعث عراق (۱۳۵۹ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 20,
    title: "روز ملی فناوری هسته‌ای",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 20,
    title: "شهادت سید مرتضی آوینی (۱۳۷۲ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 20,
    title: "روز هنر انقلاب اسلامی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 21,
    title: "شهادت امیر سپهبد علی صیاد شیرازی (۱۳۷۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 21,
    title: "سالروز افتتاح حساب شمارهٔ ۱۰۰ به فرمان حضرت امام خمینی (ره) و تأسیس بنیاد مسکن انقلاب اسلامی (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 25,
    title: "روز بزرگداشت عطار نیشابوری",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 29,
    title: "روز ارتش جمهوری اسلامی و نیروی زمینی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 1,
    day: 31,
    title: "روز گندم و نان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 1,
    title: "روز بزرگداشت سعدی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 1,
    title: "روز نثر فارسی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 1,
    title: "روز شهدای ورزشکار",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 2,
    title: "تأسیس سپاه پاسداران انقلاب اسلامی (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 2,
    title: "سالروز اعلام انقلاب فرهنگی (۱۳۵۹ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 2,
    title: "روز زمین پاک",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 3,
    title: "روز بزرگداشت شیخ بهایی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 3,
    title: "روز معماری",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 3,
    title: "سالروز شهادت امیر سپهبد قرنی (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 5,
    title: "شکست حملهٔ نظامی آمریکا به ایران در طبس (۱۳۵۹ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 7,
    title: "روز ایمنی حمل و نقل",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 9,
    title: "روز شوراها",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 10,
    title: "روز ملی خلیج فارس",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 10,
    title: "آغاز عملیات بیت‌المقدس (۱۳۶۱ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 12,
    title: "شهادت استاد مرتضی مطهری (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 12,
    title: "روز معلم",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 15,
    title: "روز بزرگداشت شیخ صدوق",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 18,
    title: "روز بیماری‌های خاص و صعب‌العلاج",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 19,
    title: "روز بزرگداشت شیخ کلینی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 19,
    title: "روز اسناد ملی و میراث مکتوب",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 20,
    title: "روز گل محمدی و گلاب",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 24,
    title: "لغو امتیاز تنباکو به فتوای آیت‌الله میرزا حسن شیرازی (۱۲۷۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 25,
    title: "روز پاسداشت زبان فارسی و بزرگداشت حکیم ابوالقاسم فردوسی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 27,
    title: "روز ارتباطات و روابط عمومی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 28,
    title: "روز بزرگداشت حکیم عمر خیام",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 30,
    title: "روز ملی جمعیت",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 30,
    title: "روز شهدای خدمت",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 31,
    title: "روز اهدای عضو، اهدای زندگی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 1,
    title: "روز بهره‌وری و بهینه‌سازی مصرف",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 1,
    title: "روز بزرگداشت ملاصدرا (صدرالمتألهین)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 3,
    title: "فتح خرمشهر در عملیات بیت‌المقدس (۱۳۶۱ ه‍.ش) و روز مقاومت، ایثار و پیروزی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 4,
    title: "روز مقاومت و پایداری",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 4,
    title: "روز دزفول",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 5,
    title: "روز نسیم مهر (روز حمایت از خانواده زندانیان)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 7,
    title: "افتتاح اولین دورهٔ مجلس شورای اسلامی (۱۳۵۹ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 14,
    title: "رحلت حضرت امام خمینی (ره) رهبر کبیر انقلاب و بنیان‌گذار جمهوری اسلامی ایران (۱۳۶۸ ه‍.ق)",
    isHoliday: true,
  },
  {
    calendar: "persian",
    month: 3,
    day: 14,
    title: "انتخاب حضرت آیت‌الله امام خامنه‌ای به رهبری (۱۳۶۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 15,
    title: "قیام خونین ۱۵ خرداد (۱۳۴۲ ه‍.ش)",
    isHoliday: true,
  },
  {
    calendar: "persian",
    month: 3,
    day: 15,
    title: "زندانی‌شدن حضرت امام خمینی (ره) به دست مأموران ستم شاهی پهلوی (۱۳۴۲ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 20,
    title: "روز صنایع دستی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 20,
    title: "روز ملی فرش",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 20,
    title: "شهادت آیت‌الله سعیدی به دست مأموران ستم‌شاهی پهلوی (۱۳۴۹ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 23,
    title: "روز شهدای اقتدار و اتحاد ملی ایران",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 26,
    title: "شهادت سربازان دلیر اسلام: بخارایی، امانی، صفار هرندی و نیک‌نژاد (۱۳۴۴ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 27,
    title: "روز جهاد کشاورزی (تشکیل جهاد سازندگی به فرمان حضرت امام خمینی (ره)) (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 29,
    title: "درگذشت دکتر علی شریعتی (۱۳۵۶ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 30,
    title: "شهادت زائران حرم رضوی (ع) به دست ایادی آمریکا (عاشورای ۱۳۷۳ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 31,
    title: "شهادت دکتر مصطفی چمران (۱۳۶۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 31,
    title: "روز بسیج استادان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 1,
    title: "سالروز صدور فرمان حضرت امام خمینی (ره) مبنی بر تأسیس سازمان تبلیغات اسلامی (۱۳۶۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 1,
    title: "روز تبلیغ و اطلاع‌رسانی دینی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 1,
    title: "روز اصناف",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 7,
    title: "شهادت مظلومانهٔ آیت‌الله دکتر بهشتی و ۷۲ تن از یاران حضرت امام خمینی (ره) با انفجار بمب به دست منافقان در دفتر مرکزی حزب جمهوری اسلامی (۱۳۶۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 7,
    title: "روز قوهٔ قضائیه",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 7,
    title: "بمباران شیمیایی شهر سردشت (۱۳۶۶ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 8,
    title: "روز مبارزه با سلاح‌های شیمیایی و میکروبی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 10,
    title: "روز صنعت و معدن",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 10,
    title: "روز دیپلماسی فرهنگی و تعامل با جهان",
    isHoliday: false,
    fromYear: 1403,
  },
  {
    calendar: "persian",
    month: 4,
    day: 10,
    title: "روز آزادسازی شهر مهران",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 10,
    title: "روز بزرگداشت صائب تبریزی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 10,
    title: "یاد روز ورود حضرت امام رضا (ع) به نیشابور و نقل حدیث سلسلةالذهب",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 11,
    title: "شهادت چهارمین شهید محراب، آیت‌الله صدوقی به دست منافقان (۱۳۶۱ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 12,
    title: "حملهٔ ددمنشانهٔ ناوگان آمریکای جنایتکار به هواپیمای مسافربری جمهوری اسلامی ایران (۱۳۶۷ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 12,
    title: "روز افشای حقوق بشر آمریکایی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 12,
    title: "روز بزرگداشت علامه امینی (۱۳۴۹ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 14,
    title: "روز قلم",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 14,
    title: "روز شهرداری و دهیاری",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 16,
    title: "روز مالیات",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 18,
    title: "روز ادبیات کودکان و نوجوانان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 18,
    title: "کشف توطئهٔ آمریکایی در پایگاه هوایی شهید نوژه (کودتای نافرجام نقاب) (۱۳۵۹ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 21,
    title: "روز عفاف و حجاب",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 21,
    title: "حمله به مسجد گوهرشاد و کشتار مردم به دست رضاخان (۱۳۱۴ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 22,
    title: "روز بزرگداشت خوارزمی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 22,
    title: "روز فناوری اطلاعات",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 23,
    title: "روز گفت‌وگو و تعامل سازنده با دنیا",
    isHoliday: false,
    fromYear: 1396,
    toYear: 1402,
  },
  {
    calendar: "persian",
    month: 4,
    day: 23,
    title: "گشایش نخستین مجلس خبرگان رهبری (۱۳۶۲ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 25,
    title: "روز بهزیستی و تأمین اجتماعی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 26,
    title: "سالروز تأسیس نهاد شورای نگهبان (۱۳۵۹ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 27,
    title: "اعلام پذیرش قطعنامهٔ ۵۹۸ شورای امنیت از سوی ایران (۱۳۶۷ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 30,
    title: "روز بزرگداشت آیت‌الله سید ابوالقاسم کاشانی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 4,
    title: "روز بزرگداشت شیخ صفی‌الدین اردبیلی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 5,
    title: "سالروز عملیات افتخار‌آفرین مرصاد (۱۳۶۷ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 5,
    title: "روز اقامهٔ اولین نماز جمعه با حکم حضرت امام خمینی (ره) در سال ۱۳۵۸",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 6,
    title: "روز کارآفرینی و آموزش‌های فنی‌و‌حرفه‌ای",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 8,
    title: "روز شعر و ادبیات آیینی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 8,
    title: "روز بزرگداشت محتشم کاشانی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 8,
    title: "روز بزرگداشت شیخ شهاب‌الدین سهروردی (شیخ اشراق)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 8,
    title: "روز زنجان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 9,
    title: "روز اهدای خون",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 11,
    title: "شهادت آیت‌الله شیخ فضل‌الله نوری (۱۲۸۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 14,
    title: "صدور فرمان مشروطیت (۱۲۸۵ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 14,
    title: "روز حقوق بشر اسلامی و کرامت انسانی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 15,
    title: "سالروز شهادت امیر سرلشکر خلبان عباس بابایی (۱۳۶۶ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 16,
    title: "تشکیل جهاد دانشگاهی (۱۳۵۹ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 17,
    title: "سالروز شهادت محمود صارمی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 17,
    title: "روز خبرنگار",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 18,
    title: "روز بزرگداشت شهدای مدافع حرم",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 21,
    title: "روز حمایت از صنایع کوچک",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 22,
    title: "روز تشکل‌ها و مشارکت‌های اجتماعی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 23,
    title: "روز مقاومت اسلامی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 26,
    title: "آغاز بازگشت آزادگان به میهن اسلامی (۱۳۶۹ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 28,
    title: "کودتای آمریکا برای بازگرداندن شاه (۱۳۳۲ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 28,
    title: "گشایش مجلس خبرگان برای بررسی نهایی قانون اساسی جمهوری اسلامی ایران (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 30,
    title: "روز بزرگداشت علامهٔ مجلسی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 31,
    title: "روز صنعت دفاعی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 5,
    day: 31,
    title: "روز عسل",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 1,
    title: "روز بزرگداشت ابوعلی سینا",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 1,
    title: "روز پزشک",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 1,
    title: "روز همدان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 2,
    title: "آغاز هفتهٔ دولت",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 2,
    title: "شهادت سید علی اندرزگو (در روز ۱۹ ماه مبارک رمضان) (۱۳۵۷ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 3,
    title: "اِشغال ایران توسط متفقین و فرار رضاخان (۱۳۲۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 4,
    title: "روز کارمند",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 5,
    title: "روز بزرگداشت محمدبن زکریای رازی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 5,
    title: "روز داروسازی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 5,
    title: "روز کُشتی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 8,
    title: "انفجار دفتر نخست‌وزیری به دست منافقان و شهادت مظلومانهٔ شهیدان رجایی و باهنر (۱۳۶۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 8,
    title: "روز مبارزه با تروریسم",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 10,
    title: "سالروز تصویب قانون عملیات بانکی بدون ربا (۱۳۶۲ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 10,
    title: "روز بانکداری اسلامی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 10,
    title: "روز تشکیل قرارگاه پدافند هوایی حضرت خاتم‌الانبیا (ص) (۱۳۷۱ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 11,
    title: "روز صنعت چاپ",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 12,
    title: "شهادت رئیسعلی دلواری (۱۲۹۴ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 12,
    title: "روز مبارزه با استعمار انگلیس",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 12,
    title: "روز بهوَرز",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 13,
    title: "روز تعاون",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 13,
    title: "روز بزرگداشت ابوریحان بیرونی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 13,
    title: "روز علوم پایه",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 13,
    title: "روز مردم‌شناسی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 13,
    title: "سالروز زلزله فردوس در سال ۱۳۴۷",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 13,
    title: "روز حرکت‌های جهادی و امداد مردمی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 14,
    title: "شهادت آیت‌الله قدوسی و سرتیپ وحید دستجردی (۱۳۶۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 17,
    title: "قیام ۱۷ شهریور و کشتار جمعی از مردم به دست مأموران ستم‌شاهی پهلوی (۱۳۵۷ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 19,
    title: "وفات آیت‌الله سیدمحمود طالقانی اولین امام جمعهٔ تهران (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 20,
    title: "شهادت دومین شهید محراب، آیت‌الله مدنی به دست منافقان (۱۳۶۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 21,
    title: "روز سینما",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 25,
    title: "روز خرما",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 27,
    title: "روز شعر و ادب فارسی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 27,
    title: "روز بزرگداشت استاد سید محمدحسین شهریار",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 31,
    title: "آغاز جنگ تحمیلی (۱۳۵۹ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 31,
    title: "آغاز هفتهٔ دفاع مقدس",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 1,
    title: "روز پرچم",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 2,
    title: "روز بزرگداشت شهدای منا",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 4,
    title: "روز سرباز",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 5,
    title: "شکست حصر آبادان در عملیات ثامن‌الائمه (ع) (۱۳۶۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 5,
    title: "روز گردشگری",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 7,
    title: "شهادت سرداران اسلام: فلاحی، فکوری، نامجو، کلاهدوز و جهان‌آرا (۱۳۶۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 7,
    title: "روز بزرگداشت فرماندهان شهید دفاع مقدس",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 7,
    title: "روز آتش‌نشانی و ایمنی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 7,
    title: "روز بزرگداشت شمس",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 8,
    title: "روز بزرگداشت مولوی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 10,
    title: "روز نخبگان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 13,
    title: "هجرت حضرت امام خمینی (ره) از عراق به پاریس (۱۳۵۷ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 13,
    title: "روز نیروی انتظامی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 14,
    title: "روز دامپزشکی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 15,
    title: "روز روستا و عشایر",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 15,
    title: "روز جهانی حماسهٔ فلسطین",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 15,
    title: "طوفان الاقصی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 20,
    title: "روز بزرگداشت حافظ",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 23,
    title: "شهادت پنجمین شهید محراب، آیت‌الله اشرفی اصفهانی به دست منافقان (۱۳۶۱ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 24,
    title: "روز ملی پارالمپیک",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 24,
    title: "روز پیوند اولیا و مربیان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 24,
    title: "سالروز واقعهٔ به آتش کشیدن مسجد جامع شهر کرمان به دست دژخیمان حکومت پهلوی (۱۳۵۷ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 25,
    title: "روز نسل‌کشی کودکان و زنان فلسطینی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 26,
    title: "روز تربیت‌بدنی و ورزش",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 29,
    title: "روز صادرات",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 1,
    title: "شهادت مظلومانهٔ آیت‌الله حاج سید مصطفی خمینی (۱۳۵۶ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 1,
    title: "روز آمار و برنامه‌ریزی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 1,
    title: "روز بزرگداشت ابوالفضل بیهقی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 4,
    title: "اعتراض و افشاگری حضرت امام خمینی (ره) علیه پذیرش کاپیتولاسیون (۱۳۴۳ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 5,
    title: "روز زعفران",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 7,
    title: "روز انار",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 8,
    title: "شهادت محمدحسین فهمیده (بسیجی ۱۳ ساله) (۱۳۵۹ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 8,
    title: "روز نوجوان و بسیج دانش‌آموزی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 8,
    title: "روز پدافند غیرعامل",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 10,
    title: "شهادت اولین شهید محراب، آیت‌الله قاضی طباطبایی به دست منافقان (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 13,
    title: "تسخیر لانهٔ جاسوسی آمریکا به دست دانشجویان پیرو خط حضرت امام (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 13,
    title: "روز ملی مبارزه با استکبار جهانی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 13,
    title: "روز دانش‌آموز",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 13,
    title: "تبعید حضرت امام خمینی (ره) از ایران به ترکیه (۱۳۴۳ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 14,
    title: "روز فرهنگ عمومی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 14,
    title: "روز مازندران",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 18,
    title: "روز کیفیت",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 21,
    title: "روز هوافضا",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 24,
    title: "روز کتاب، کتاب‌خوانی و کتابدار",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 24,
    title: "روز بزرگداشت آیت‌الله علامه سید محمّدحسین طباطبایی (۱۳۶۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 25,
    title: "روز اصفهان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 26,
    title: "سالروز آزادسازی سوسنگرد",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 30,
    title: "روز قهرمان ملی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 30,
    title: "روز بزرگداشت ابونصر فارابی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 30,
    title: "روز حکمت و فلسفه",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 4,
    title: "روز زیتون",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 5,
    title: "تشکیل بسیج مستضعفان به فرمان حضرت امام خمینی (ره) (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 5,
    title: "روز بسیج مستضعفان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 5,
    title: "سالروز قیام مردم گرگان (۱۳۵۷ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 7,
    title: "روز نیروی دریایی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 7,
    title: "روز نوآوری و فناوری ایران‌ساخت",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 9,
    title: "روز بزرگداشت شیخ مفید",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 9,
    title: "روز جزایر سه‌گانهٔ خلیج فارس (بوموسی، تنب بزرگ و تنب کوچک)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 10,
    title: "شهادت آیت‌الله سید حسن مدرس (۱۳۱۶ ه‍.ش) و روز مجلس",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 11,
    title: "شهادت میرزا کوچک‌خان جنگلی (۱۳۰۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 12,
    title: "تصویب قانون اساسی جمهوری اسلامی ایران (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 12,
    title: "روز قانون اساسی جمهوری اسلامی ایران",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 13,
    title: "روز بیمه",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 16,
    title: "روز دانشجو",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 18,
    title: "معرفی عراق به عنوان مسئول و آغازگر جنگ از سوی سازمان ملل (۱۳۷۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 19,
    title: "تشکیل شورای عالی انقلاب فرهنگی به فرمان حضرت امام خمینی (ره) (۱۳۶۳ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 20,
    title: "شهادت سومین شهید محراب، آیت‌الله دستغیب به دست منافقان (۱۳۶۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 25,
    title: "روز پژوهش",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 26,
    title: "روز حمل‌و‌نقل و رانندگان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 27,
    title: "شهادت آیت‌الله دکتر محمد مفتح (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 27,
    title: "روز وحدت حوزه و دانشگاه",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 27,
    title: "روز جهان عاری از خشونت و افراطی‌گری",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 29,
    title: "روز تجلیل از شهید تندگویان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 30,
    title: "شب یلدا (چله)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 30,
    title: "ترویج فرهنگ میهمانی و پیوند با خویشان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 3,
    title: "روز ثبت احوال",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 4,
    title: "روز بزرگداشت رودکی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 5,
    title: "روز ایمنی در برابر زلزله و کاهش اثرات بلایای طبیعی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 7,
    title: "سالروز تشکیل نهضت سوادآموزی به فرمان حضرت امام خمینی (ره) (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 7,
    title: "شهادت آیت‌الله حسین غفاری به دست مأموران ستم‌شاهی پهلوی (۱۳۵۳ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 8,
    title: "روز صنعت پتروشیمی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 9,
    title: "روز بصیرت و میثاق امت با ولایت",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 12,
    title: "روز بزرگداشت علامه مصباح یزدی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 12,
    title: "روز علوم انسانی اسلامی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 13,
    title: "روز جهانی مقاومت",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 13,
    title: "شهادت الگوی اخلاص و عمل سردار سپهبد قاسم سلیمانی به دست استکبار جهانی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 13,
    title: "ابلاغ پیام تاریخی حضرت امام خمینی (ره) به گورباچف رهبر شوروی سابق (۱۳۶۷ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 16,
    title: "شهادت سیدحسین علم‌الهدی و همرزمان وی در هویزه",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 16,
    title: "روز شهدای دانشجو",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 17,
    title: "اجرای طرح استعماری حذف حجاب (کشف حجاب) به دست رضاخان (۱۳۱۴ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 17,
    title: "روز بزرگداشت خواجوی کرمانی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 17,
    title: "روز کرمان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 19,
    title: "قیام خونین مردم قم (۱۳۵۶ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 20,
    title: "شهادت میرزا تقی‌خان امیرکبیر (۱۲۳۰ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 22,
    title: "تشکیل شورای انقلاب به فرمان حضرت امام خمینی (ره) (۱۳۵۷ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 25,
    title: "روز تاریخ‌نگاری انقلاب اسلامی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 26,
    title: "فرار شاه معدوم (۱۳۵۷ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 27,
    title: "شهادت نواب صفوی، طهماسبی، برادران واحدی و ذوالقدر از فدائیان اسلام (۱۳۳۴ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 11,
    day: 1,
    title: "روز بزرگداشت خاقانی شروانی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 11,
    day: 6,
    title: "سالروز حماسهٔ مردم آمل",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 11,
    day: 6,
    title: "روز بزرگداشت صفی‌الدین اُرمَوی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 11,
    day: 6,
    title: "روز آواها و نواهای ایرانی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 11,
    day: 12,
    title: "سالروز بازگشت حضرت امام خمینی (ره) به ایران و آغاز دههٔ مبارک فجر انقلاب اسلامی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 11,
    day: 14,
    title: "روز فناوری فضایی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 11,
    day: 19,
    title: "روز نیروی هوایی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 11,
    day: 1,
    title: "روز چهارمحال و بختیاری",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 11,
    day: 21,
    title: "شکسته‌شدن حکومت‌نظامی به فرمان حضرت امام خمینی (ره) (۱۳۵۷ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 11,
    day: 22,
    title: "پیروزی انقلاب اسلامی ایران و سقوط نظام شاهنشاهی (۱۳۵۷ ه‍.ش)",
    isHoliday: true,
  },
  {
    calendar: "persian",
    month: 11,
    day: 25,
    title: "صدور حکم تاریخی حضرت امام خمینی (ره) مبنی بر ارتداد سلمان‌رشدی نویسندهٔ خائن کتاب آیات شیطانی (۱۳۶۷ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 11,
    day: 29,
    title: "قیام مردم تبریز به مناسبت چهلمین روز شهادت شهدای قم (۱۳۵۶ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 11,
    day: 29,
    title: "روز اقتصاد مقاومتی و کارآفرینی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 3,
    title: "کودتای انگلیسی رضاخان (۱۲۹۹ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 5,
    title: "روز بزرگداشت خواجه نصیرالدین طوسی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 5,
    title: "روز مهندسی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 8,
    title: "روز امور تربیتی و تربیت اسلامی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 8,
    title: "روز بزرگداشت حکیم حاج ملاهادی سبزواری",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 8,
    title: "روز حمایت از بیماران نادر",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 9,
    title: "روز حمایت از حقوق مصرف‌کنندگان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 14,
    title: "روز احسان و نیکوکاری",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 14,
    title: "روز ترویج فرهنگ قرض‌الحسنه",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 15,
    title: "روز درختکاری",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 15,
    title: "روز آموزش همگانی حفظ محیط زیست",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 18,
    title: "روز بزرگداشت سید جمال‌الدین اسدآبادی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 18,
    title: "سالروز تأسیس کانون‌های فرهنگی و هنری مساجد کشور",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 18,
    title: "روز بوشهر",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 20,
    title: "روز راهیان نور",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 21,
    title: "روز بزرگداشت نظامی گنجوی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 22,
    title: "سالروز صدور فرمان حضرت امام خمینی (ره)، مبنی بر تأسیس بنیاد شهید انقلاب اسلامی (۱۳۵۸ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 22,
    title: "روز بزرگداشت شهدا",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 25,
    title: "روز بزرگداشت پروین اعتصامی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 25,
    title: "بمباران شیمیایی حلبچه به دست ارتش بعث عراق (۱۳۶۶ ه‍.ش)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 29,
    title: "روز ملی‌شدن صنعت نفت ایران (۱۳۲۹ ه‍.ش)",
    isHoliday: true,
  },
  {
    calendar: "persian",
    month: 1,
    day: 30,
    title: "روز آزمایشگاهیان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 9,
    title: "روز روان‌شناس و مشاور",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 15,
    title: "روز صنعت بتن آماده",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 15,
    title: "روز صنعت تهویه مطبوع",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 22,
    title: "روز مشاغل خانگی و تولید خانواده‌محور",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 2,
    day: 31,
    title: "روز بوم‌گردی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 7,
    title: "روز نقشه‌برداری",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 8,
    title: "روز مشاور املاک",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 3,
    day: 30,
    title: "روز صنعت موتورسیکلت",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 5,
    title: "روز صنعت ابزارآلات",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 6,
    title: "روز عینک‌سازی و بینایی‌سنجی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 12,
    title: "روز حمایت از تولید ملی و مبارزه با قاچاق کالا",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 12,
    title: "روز خیاط، صنعت نساجی و پوشاک",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 18,
    title: "روز صنعت قیر و آسفالت",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 4,
    day: 30,
    title: "روز خلبان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 25,
    title: "روز کفاش، صنعت کفش و چرم",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 6,
    day: 26,
    title: "روز فوریت‌های پزشکی (اورژانس)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 7,
    day: 24,
    title: "روز صنعت آسانسور و پله‌برقی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 1,
    title: "روز صنعت ساختمان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 8,
    title: "روز محیط‌بان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 8,
    day: 25,
    title: "روز صنعت نوشت‌افزار",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 1,
    title: "روز صنعت سرب و روی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 15,
    title: "روز حسابدار",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 18,
    title: "روز سد و نیروگاه برق‌آبی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 9,
    day: 22,
    title: "روز صنعت مس",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 1,
    title: "روز آرایشگر",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 6,
    title: "روز دفاتر اسناد رسمی",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 8,
    title: "روز صنعت سیمان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 20,
    title: "روز قناد، صنعت شیرینی و شکلات",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 10,
    day: 29,
    title: "روز معاینه فنی خودرو",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 11,
    day: 11,
    title: "روز ویراستار",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 10,
    title: "روز بازاریاب و مدیر فروش",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 16,
    title: "روز کارشناس و متخصص تغذیه",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 21,
    title: "روز خادمان آرامستان",
    isHoliday: false,
  },
  {
    calendar: "persian",
    month: 12,
    day: 23,
    title: "روز صنعت طلا، جواهر، نقره و گوهرسنگ‌ها",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 1,
    day: 1,
    title: "آغاز سال هجری قمری",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 1,
    day: 2,
    title: "روز امر به معروف و نهی از منکر",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 1,
    day: 9,
    title: "تاسوعای حسینی",
    isHoliday: true,
    fromYear: 1272,
  },
  {
    calendar: "hijri",
    month: 1,
    day: 10,
    title: "عاشورای حسینی",
    isHoliday: true,
    fromYear: 1272,
  },
  {
    calendar: "hijri",
    month: 1,
    day: 11,
    title: "روز تجلیل از اسرا و مفقودان",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 1,
    day: 12,
    title: "شهادت حضرت امام زین‌العابدین (ع) (۹۵ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 1,
    day: 25,
    title: "شهادت حضرت امام زین‌العابدین (ع) (۹۵ ه‍.ق) به روایتی",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 1,
    day: 25,
    title: "یاد روز قیام مردم سیستان به خون‌خواهی شهدای کربلا (سال ۶۲ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 2,
    day: 3,
    title: "ولادت حضرت امام محمد باقر (ع) (۵۷ ﻫ.ق) به روایتی",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 2,
    day: 7,
    title: "شهادت حضرت امام حسن مجتبی (ع) (۵۰ ه‍.ق) به روایتی",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 2,
    day: 7,
    title: "روز بزرگداشت سلمان فارسی",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 2,
    day: 20,
    title: "اربعین حسینی",
    isHoliday: true,
    fromYear: 1272,
  },
  {
    calendar: "hijri",
    month: 2,
    day: 28,
    title: "رحلت حضرت رسول اکرم (ص) (۱۱ ه‍.ق) – شهادت حضرت امام حسن مجتبی (ع) (۵۰ ه‍.ق)",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    month: 3,
    day: 1,
    title: "هجرت رسول اکرم (ص) از مکه به مدینه",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 3,
    day: 8,
    title: "شهادت حضرت امام حسن عسکری (ع) (۲۶۰ ه‍.ق) و آغاز امامت حضرت ولی عصر (عج)",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    month: 3,
    day: 12,
    title: "ولادت حضرت رسول اکرم (ص) به روایت اهل سنت (۵۳ سال قبل از هجرت)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 3,
    day: 12,
    title: "آغاز هفتهٔ وحدت",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 3,
    day: 14,
    title: "روز سیستان و بلوچستان",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 3,
    day: 16,
    title: "روز وقف",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 3,
    day: 17,
    title: "ولادت حضرت رسول اکرم (ص) (۵۳ سال قبل از هجرت) و روز اخلاق و مهرورزی",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    month: 3,
    day: 17,
    title: "ولادت حضرت امام جعفر صادق (ع) مؤسس مذهب جعفری (۸۳ ه‍.ق)",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    month: 4,
    day: 4,
    title: "ولادت حضرت عبدالعظیم حسنی (ع)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 4,
    day: 8,
    title: "ولادت حضرت امام حسن عسکری (ع) (۲۳۲ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 4,
    day: 10,
    title: "وفات حضرت معصومه (س) (۲۰۱ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 5,
    day: 5,
    title: "ولادت حضرت زینب (س) (۵ ه‍.ق) و روز پرستار",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 5,
    day: 13,
    title: "شهادت حضرت فاطمهٔ زهرا (س) (۱۱ ه‍.ق) به روایتی",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 6,
    day: 3,
    title: "شهادت حضرت فاطمهٔ زهرا (س) (۱۱ ه‍.ق)",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    month: 6,
    day: 13,
    title: "سالروز وفات حضرت ام‌البنین (س)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 6,
    day: 13,
    title: "روز تکریم مادران و همسران شهدا",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 6,
    day: 20,
    title: "ولادت حضرت فاطمهٔ زهرا (س) (سال هشتم قبل از هجرت) و روز زن",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 6,
    day: 20,
    title: "تولد حضرت امام خمینی (ره) رهبر کبیر انقلاب اسلامی (۱۳۲۰ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 7,
    day: 1,
    title: "ولادت حضرت امام محمد باقر (ع) (۵۷ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 7,
    day: 3,
    title: "شهادت حضرت امام علی النقی الهادی (ع) (۲۵۴ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 7,
    day: 10,
    title: "ولادت حضرت امام محمد تقی (ع) «جوادالائمه» (۱۹۵ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 7,
    day: 13,
    title: "ولادت حضرت امام علی (ع) (۲۳ سال قبل از هجرت)",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    month: 7,
    day: 13,
    title: "روز پدر",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 7,
    day: 13,
    title: "آغاز ایام‌البیض (اعتکاف)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 7,
    day: 15,
    title: "ارتحال حضرت زینب (س) (۶۲ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 7,
    day: 15,
    title: "تغییر قبلهٔ مسلمین از بیت‌المقدس به مکهٔ معظمه (۲ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 7,
    day: 25,
    title: "شهادت حضرت امام موسی کاظم (ع) (۱۸۳ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 7,
    day: 27,
    title: "مبعث حضرت رسول اکرم (ص) (۱۳ سال قبل از هجرت)",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    month: 8,
    day: 3,
    title: "ولادت حضرت امام حسین (ع) (۴ ه‍.ق) و روز پاسدار",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 8,
    day: 4,
    title: "ولادت حضرت ابوالفضل العباس (ع) (۲۶ ه‍.ق) و روز جانباز",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 8,
    day: 5,
    title: "ولادت حضرت امام زین‌العابدین (ع) (۳۸ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 8,
    day: 5,
    title: "روز صحیفهٔ سجادیه",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 8,
    day: 11,
    title: "ولادت حضرت علی اکبر (ع) (۳۳ ه‍.ق) و روز جوان",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 8,
    day: 15,
    title: "ولادت حضرت قائم (عج) (۲۵۵ ه‍.ق) و روز جهانی مستضعفان",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    month: 8,
    day: 15,
    title: "روز سربازان گمنام حضرت امام زمان (عج)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 9,
    day: 10,
    title: "وفات حضرت خدیجه (س) (۳ سال قبل از هجرت)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 9,
    day: 15,
    title: "ولادت حضرت امام حسن مجتبی (ع) (۳ ه‍.ق) و روز اکرام و تکریم خیرین",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 9,
    day: 18,
    title: "شب قدر",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 9,
    day: 19,
    title: "ضربت خوردن حضرت امام علی (ع) (۴۰ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 9,
    day: 19,
    title: "روز نهج‌البلاغه",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 9,
    day: 20,
    title: "شب قدر",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 9,
    day: 21,
    title: "شهادت حضرت امام علی (ع) (۴۰ ه‍.ق)",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    month: 9,
    day: 22,
    title: "شب قدر",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 10,
    day: 1,
    title: "عید سعید فطر",
    isHoliday: true,
    fromYear: 1272,
  },
  {
    calendar: "hijri",
    month: 10,
    day: 2,
    title: "تعطیل به مناسبت عید سعید فطر",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    month: 10,
    day: 17,
    title: "روز فرهنگ پهلوانی و ورزش زورخانه‌ای",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 10,
    day: 21,
    title: "فتح اندلس به دست مسلمانان (۹۲ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 10,
    day: 25,
    title: "شهادت حضرت امام جعفر صادق (ع) (۱۴۸ ه‍.ق)",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    month: 11,
    day: 1,
    title: "ولادت حضرت معصومه (س) (۱۷۳ ه‍.ق) و روز دختران",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 11,
    day: 1,
    title: "آغاز دههٔ کرامت",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 11,
    day: 5,
    title: "روز تجلیل از امامزادگان و بقاع متبرکه",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 11,
    day: 5,
    title: "روز بزرگداشت حضرت صالح بن موسی کاظم (ع)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 11,
    day: 6,
    title: "روز بزرگداشت حضرت احمدبن‌موسی شاهچراغ (ع)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 11,
    day: 11,
    title: "ولادت حضرت امام رضا (ع) (۱۴۸ ه‍.ق)",
    isHoliday: false,
    fromYear: 1272,
  },
  {
    calendar: "hijri",
    month: 12,
    day: 1,
    title: "سالروز ازدواج حضرت امام علی (ع) و حضرت فاطمه (س) (۲ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 12,
    day: 1,
    title: "روز ازدواج",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 12,
    day: 6,
    title: "شهادت مظلومانهٔ زائران خانهٔ خدا به دست مأموران آل سعود (۱۳۶۶ ه‍.ش برابر با ۶ ذی‌الحجه ۱۴۰۷ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 12,
    day: 7,
    title: "شهادت حضرت امام محمد باقر (ع) (۱۱۴ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 12,
    day: 9,
    title: "روز عرفه (روز نیایش)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 12,
    day: 10,
    title: "عید سعید قربان",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    month: 12,
    day: 10,
    title: "آغاز دههٔ امامت و ولایت",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 12,
    day: 15,
    title: "ولادت حضرت امام علی النقی الهادی (ع) (۲۱۲ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 12,
    day: 18,
    title: "عید سعید غدیر خم (۱۰ ه‍.ق)",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    month: 12,
    day: 20,
    title: "ولادت حضرت امام موسی کاظم (ع) (۱۲۸ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 12,
    day: 24,
    title: "روز مباهلهٔ پیامبر اسلام (ص) (۱۰ ه‍.ق)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    month: 12,
    day: 25,
    title: "روز خانواده و تکریم بازنشستگان",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 1,
    day: 1,
    title: "آغاز سال میلادی",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 1,
    day: 26,
    title: "روز جهانی گمرک",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 3,
    day: 22,
    title: "روز جهانی آب",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 3,
    day: 23,
    title: "روز جهانی هواشناسی",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 4,
    day: 5,
    title: "روز جهانی کودک فلسطینی",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 5,
    day: 1,
    title: "روز جهانی کار و کارگر",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 5,
    day: 5,
    title: "روز جهانی ماما",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 5,
    day: 8,
    title: "روز جهانی صلیب سرخ و هلال احمر",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 5,
    day: 18,
    title: "روز جهانی موزه و میراث فرهنگی",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 5,
    day: 31,
    title: "روز جهانی بدون دخانیات",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 6,
    day: 1,
    title: "روز جهانی والدین",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 6,
    day: 5,
    title: "روز جهانی محیط زیست",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 6,
    day: 17,
    title: "روز جهانی بیابان‌زدایی",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 6,
    day: 26,
    title: "روز جهانی مبارزه با مواد مخدر",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 8,
    day: 1,
    title: "روز جهانی شیر مادر",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 8,
    day: 6,
    title: "انفجار بمب اتمی آمریکا در هیروشیما با بیش از ۱۶۰هزار کشته و مجروح (۱۹۴۵ میلادی)",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 8,
    day: 21,
    title: "روز جهانی مسجد",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 9,
    day: 27,
    title: "روز جهانی جهانگردی",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 9,
    day: 30,
    title: "روز جهانی دریانوردی",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 9,
    day: 30,
    title: "روز جهانی ناشنوایان",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 10,
    day: 1,
    title: "روز جهانی سالمندان",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 10,
    day: 8,
    title: "روز جهانی کودک",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 10,
    day: 9,
    title: "روز جهانی پست",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 10,
    day: 14,
    title: "روز جهانی استاندارد",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 10,
    day: 15,
    title: "روز جهانی نابینایان (عصای سفید)",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 10,
    day: 16,
    title: "روز جهانی غذا",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 11,
    day: 10,
    title: "روز جهانی علم در خدمت صلح و توسعه",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 12,
    day: 1,
    title: "روز جهانی مبارزه با ایدز",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 12,
    day: 3,
    title: "روز جهانی معلولان",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 12,
    day: 7,
    title: "روز جهانی هواپیمایی",
    isHoliday: false,
  },
  {
    calendar: "gregorian",
    month: 12,
    day: 25,
    title: "ولادت حضرت عیسی مسیح (ع)",
    isHoliday: false,
  },
];

export const IRREGULAR_OCCASIONS: readonly IrregularOccasionRecord[] = [
  {
    calendar: "persian",
    rule: "nth-weekday",
    month: 7,
    nth: 2,
    weekday: 6,
    title: "آیین مذهبی قالیشویان اردهال (دومین جمعهٔ مهر)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    rule: "nth-weekday",
    month: 7,
    nth: 2,
    weekday: 6,
    title: "بزرگداشت امامزاده علی بن محمدباقر (ع) (دومین جمعهٔ مهر)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    rule: "single",
    year: 1401,
    month: 8,
    day: 3,
    title: "خورشیدگرفتگی جزئی قابل مشاهده در ایران",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    rule: "end-of-month",
    month: 2,
    title: "شهادت حضرت امام رضا (ع) (۲۰۳ ه‍.ق) (۳۰ صَفَر یا انتهای ماه)",
    isHoliday: true,
  },
  {
    calendar: "hijri",
    rule: "end-of-month",
    month: 11,
    title: "شهادت حضرت امام محمد تقی (ع) (۲۲۰ ه‍.ق) (۳۰ ذی‌القعده یا انتهای ماه)",
    isHoliday: false,
  },
  {
    calendar: "hijri",
    rule: "last-weekday",
    month: 9,
    weekday: 6,
    title: "روز جهانی قدس (آخرین جمعهٔ رمضان)",
    isHoliday: false,
  },
  {
    calendar: "persian",
    rule: "last-weekday",
    month: 12,
    weekday: 4,
    offset: -1,
    title: "روز تکریم همسایگان (شب آخرین چهارشنبهٔ سال)",
    isHoliday: false,
  },
];

export const HIJRI_YEAR_MASKS: readonly number[] = [
  2711, 2730, 2773, 1428, 2986, 1461, 1206, 2647, 1323, 1699, 1745, 2793,
  1386, 2669, 1325, 3221, 3658, 3749, 1716, 2490, 1339, 603, 1323, 2645,
  2730, 2905, 1396, 2426, 1210, 2650, 3380, 3761, 1752, 2796, 1372, 2670,
  1334, 2726, 2898, 2985, 948, 2522, 1370, 2730, 3402, 3749, 1874, 2921,
  1460, 2733, 1622, 3366, 3730, 3913, 1876, 2906, 2459, 1179, 2379, 2853,
  3410, 3434, 1389, 694, 2615, 1179, 1613, 1706, 2901, 860, 2414, 1199,
  599, 811, 1429, 938, 1497, 730, 2397, 683, 1365, 1737, 1764, 2922,
  1461, 694, 2454, 3402, 3525, 1874, 1957, 874, 2477, 1357, 2709, 3401,
  3493, 1458, 2773, 1366, 2647, 1323, 1685, 2890, 2917, 1387, 685, 1358,
  3223, 1355, 1701, 1746, 2777, 1245, 599, 2349, 2709, 2898, 2921, 884,
  2422, 1207, 599, 1355, 1701, 1746, 2794, 1261, 621, 2357, 3365, 3409,
  2985, 1492, 2741, 1334, 2711, 1610, 3749, 1874, 2985, 1461, 693, 2646,
  3366, 3667, 1705, 3412, 3414, 2647, 1191, 3143, 3366, 3668, 3494, 1383,
  694, 2359, 1175, 1621, 2730, 2917, 748, 2421, 1134, 2614, 3238, 3410,
  3538, 1493, 730, 1373, 1195, 1683, 1865, 1956, 2994, 1461, 694, 1626,
  3370, 3732, 3793, 1768, 2794, 2396,
];

export const HIJRI_TABLE_START_YEAR = 1264;
export const HIJRI_TABLE_START_JDN = 2_396_005;
